[install]
exact = true
minimumReleaseAge = 259200
ignoreScripts = true
minimumReleaseAgeExcludes = ["@navikt/klage-e2e-reporters"]

[install.scopes]
"@navikt" = { url = "https://npm.pkg.github.com", token = "$READER_TOKEN" }
